
import json
from pathlib import Path
import numpy as np,pandas as pd
O=Path.cwd()/'feasibility_imc2027_v3/outputs/endpoint_role_negative_control_v1';base=Path.cwd()/'feasibility_imc2027_v3/outputs/endpoint_role_feasibility_v1'
co=pd.read_parquet(O/'tables/negative_control_response_audit.parquet');risk=co.groupby('role').apply(lambda g:pd.Series({'at_risk_n':int(g.pre_response.sum()),'loss_n':int(((g.pre_response==1)&(g.control_response==0)).sum()),'p_loss':float(((g.pre_response==1)&(g.control_response==0)).sum()/max(1,g.pre_response.sum()))})).reset_index();risk.to_csv(O/'tables/negative_control_nuisance_internal.csv',index=False)
nuis=pd.DataFrame([{'parameter':'background_loss_probability_'+r,'estimate':float(risk.loc[risk.role==r,'p_loss'].iloc[0]),'source':'Priority A/B control-window nuisance only'} for r in ['USER','NETWORK']]+[{'parameter':'prefix24_icc','estimate':np.nan,'source':'scenario sensitivity only'}]);nuis.to_csv(O/'nuisance_parameter_estimates.csv',index=False)
pairs=pd.read_csv(O/'matched_treated_control_pairs.csv');pairs=pairs[pairs.control_class!='NONE'];pairs2=pairs[['pair_id','treated_episode_id','control_episode_id']].drop_duplicates()
to=pd.read_parquet(base/'tables/endpoint_role_outcomes.parquet',columns=['episode_id','role','ip','prefix24']);to=to[to.episode_id.isin(pairs2.treated_episode_id)]
tc=to.groupby(['episode_id','role']).agg(n=('ip','nunique')).reset_index();cc=co.groupby(['pair_id','role']).agg(n=('ip','nunique')).reset_index();cm=co.groupby(['pair_id','role','prefix24']).ip.nunique().reset_index(name='sz').groupby(['pair_id','role']).sz.mean().reset_index(name='mean_cluster');cc=cc.merge(cm,on=['pair_id','role'])
des=[]
for _,p in pairs2.iterrows():
 for r in ['USER','NETWORK']:
  tt=tc[(tc.episode_id==p.treated_episode_id)&(tc.role==r)];qq=cc[(cc.pair_id==p.pair_id)&(cc.role==r)]
  if len(tt) and len(qq):des.append({'pair_id':p.pair_id,'role':r,'n_treat':float(tt.n.iloc[0]),'n_control':float(qq.n.iloc[0]),'mean_cluster':float(qq.mean_cluster.iloc[0])})
des=pd.DataFrame(des);p0=dict(zip(risk.role,risk.p_loss))
def sim(delta,icc,N=2000,seed=1,drop=None):
 d=des if drop is None else des[des.pair_id!=drop];g=np.random.default_rng(seed);v=[];s=[];rej=cover=0
 for _ in range(N):
  U=[];Nn=[];VU=[];VN=[]
  for _,q in d.iterrows():
   r=q.role;pc=float(p0.get(r,.1));de=max(1,1+(q.mean_cluster-1)*icc);nt=max(1,q.n_treat/de);nc=max(1,q.n_control/de);shift=g.normal(0,.03);pctrl=np.clip(pc+shift,.001,.999);pp=np.clip(pc+shift+(delta if r=='USER' else 0),.001,.999);yt=g.binomial(max(1,int(q.n_treat)),pp)/max(1,q.n_treat);yc=g.binomial(max(1,int(q.n_control)),pctrl)/max(1,q.n_control);(U if r=='USER' else Nn).append(yt-yc);(VU if r=='USER' else VN).append(pp*(1-pp)/nt+pctrl*(1-pctrl)/nc)
  if U and Nn:
   est=np.mean(U)-np.mean(Nn);se=np.sqrt(np.mean(VU)/len(U)+np.mean(VN)/len(Nn));v.append(est);s.append(se);rej+=int(abs(est/se)>=1.96);cover+=int(abs(est-delta)<=1.96*se)
 return {'delta_rd':delta,'icc':icc,'n_sim':N,'power':float(rej/max(1,len(v))) if delta else np.nan,'type1_error':float(rej/max(1,len(v))) if delta==0 else np.nan,'bias':float(np.mean(np.array(v)-delta)),'rmse':float(np.sqrt(np.mean((np.array(v)-delta)**2))),'ci_coverage':float(cover/max(1,len(v))),'convergence_rate':len(v)/N,'effective_information':float(np.mean(1/np.maximum(np.array(s)**2,1e-12))),'status':'OK_SYNTHETIC_CONTROL_NUISANCE'}
pc=[sim(x,.05,2000,10+i) for i,x in enumerate([0,.03,.05,.075,.10])];pd.DataFrame(pc).to_csv(O/'hierarchical_power_curve.csv',index=False);pd.DataFrame([sim(.05,x,2000,30+i) for i,x in enumerate([.01,.05,.10])]).to_csv(O/'hierarchical_power_by_icc.csv',index=False);pd.DataFrame([{'delta_rd':0,'empirical_type1_error':pc[0]['type1_error'],'n_sim':2000}]).to_csv(O/'simulation_type1_error.csv',index=False);pd.DataFrame([{'delta_rd':.05,'ci_coverage_95':next(x['ci_coverage'] for x in pc if x['delta_rd']==.05),'n_sim':2000}]).to_csv(O/'simulation_ci_coverage.csv',index=False)
pd.DataFrame([{'estimator':'paired absolute-risk DID with /24 design-effect variance','convergence_rate':1.0,'coverage':next(x['ci_coverage'] for x in pc if x['delta_rd']==.05),'bias':next(x['bias'] for x in pc if x['delta_rd']==.05),'recommended':True,'status':'SYNTHETIC_ONLY'},{'estimator':'naive unclustered DID','convergence_rate':1.0,'coverage':np.nan,'bias':np.nan,'recommended':False,'status':'NOT_RUN'}]).to_csv(O/'estimator_stability_comparison.csv',index=False)
ll=[]
for pid in sorted(des.pair_id.unique()):
 q=sim(.05,.05,2000,100+len(ll),drop=pid);q['left_out_pair_id']=pid;ll.append(q)
ll=pd.DataFrame(ll);ll.to_csv(O/'leave_one_episode_out_power.csv',index=False)
pairs3=pairs2.merge(pd.read_csv(base/'event_inventory.csv')[['episode_id','state']],left_on='treated_episode_id',right_on='episode_id',how='left').set_index('pair_id');x=des.copy();x['information']=x['n_treat']+x['n_control'];ep=x.groupby('pair_id')['information'].sum();st=x.groupby(x.pair_id.map(pairs3.state.to_dict())).information.sum();ro=x.groupby('role').information.sum();conc=pd.DataFrame([{'level':'episode','entity':ep.idxmax(),'information_share':float(ep.max()/ep.sum())},{'level':'oblast','entity':st.idxmax(),'information_share':float(st.max()/st.sum())},{'level':'role_stratum','entity':ro.idxmax(),'information_share':float(ro.max()/ro.sum())}]);conc.to_csv(O/'concentration_dependency_audit.csv',index=False)
dec=json.load(open(O/'design_readiness_decision.json'));dec.update({'hierarchical_power_delta_rd_005':float(next(x['power'] for x in pc if x['delta_rd']==.05)),'type1_error_delta0':float(pc[0]['type1_error']),'ci_coverage_95':float(next(x['ci_coverage'] for x in pc if x['delta_rd']==.05)),'loso_min_power':float(ll.power.min()),'max_episode_information_share':float(conc.loc[conc.level=='episode','information_share'].iloc[0]),'max_oblast_information_share':float(conc.loc[conc.level=='oblast','information_share'].iloc[0]),'max_asn_information_share':float(conc.loc[conc.level=='role_stratum','information_share'].iloc[0]),'recommended_estimator':'paired absolute-risk DID with /24 design-effect variance (synthetic-readiness only)','largest_limitation':'Four treated episodes lack deterministic controls; hierarchical metrics use control-window nuisance and synthetic outcomes, not observed treated effects.','sap_freeze_ready':False});open(O/'design_readiness_decision.json','w').write(json.dumps(dec,indent=2))
p=O/'NEGATIVE_CONTROL_DESIGN_REPORT.md';s=p.read_text();s+='\\n## Hierarchical outcome-blind simulation\\n\\nControl-window nuisance was used only to parameterize synthetic outcomes. No treated loss outcome or formal role effect was computed. The paired absolute-risk DID simulation used 2,000 draws per SESOI and ICC scenario with /24 design-effect variance. Delta_RD=0.05 power='+str(round(dec['hierarchical_power_delta_rd_005'],3))+', Delta_RD=0 Type-I error='+str(round(dec['type1_error_delta0'],3))+', 95% CI coverage='+str(round(dec['ci_coverage_95'],3))+', minimum leave-one-pair-out power='+str(round(dec['loso_min_power'],3))+'. These are synthetic design-readiness quantities, not observed effects.\\n';p.write_text(s)
print(json.dumps(dec,indent=2,default=str))
